using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Flags_csharp.src.datas
{
    class CountriesDatas
    {
        public class Countries
        {
            public string country ;
            public string capitale ;
            public string continent ;
            public string flag ;

            public Countries(string country, string capitale, string continent, string iso)
            {
                this.country = country;
                this.capitale = capitale;
                this.continent = continent;
                this.flag = iso;
            }
        }

        public static Countries GetCountryById(int id)
        {
            return countriesDatas[id];
        }

        public static List<Countries> countriesDatas = new List<Countries>(){
                new Countries("Afghanistan", "Kaboul", "Asie", "af"),
                new Countries("Afrique du Sud", "Pretoria", "Afrique", "za"),
                new Countries("Albanie"                          , "Tirana"              , "Europe"  , "al"),
                new Countries("Algerie"                          , "Alger"               , "Afrique" , "dz"),
                new Countries("Allemagne"                        , "Berlin"              , "Europe"  , "de"),
                new Countries("Andorre"                          , "Andorre-la-Vieille"  , "Europe"  , "ad"),
                new Countries("Angola"                           , "Luanda"              , "Afrique" , "ao"),
                new Countries("Antigua-et-Barbuda"               , "Saint John's"        , "Amerique", "ag"),
                new Countries("Arabie Saoudite"                  , "Riyad"               , "Asie"    , "sa"),
                new Countries("Argentine"                        , "Buenos Aires"        , "Amerique", "ar"),
                new Countries("Armenie"                          , "Erevan"              , "Asie"    , "am"),
                new Countries("Australie"                        , "Canberra"            , "Oceanie" , "au"),
                new Countries("Autriche"                         , "Vienne"              , "Europe"  , "at"),
                new Countries("Azerbaidjan"                      , "Bakou"               , "Asie"    , "az"),
                new Countries("Bahamas"                          , "Nassau"              , "Amerique", "bs"),
                new Countries("Bahrein"                          , "Manama"              , "Asie"    , "bh"),
                new Countries("Bangladesh"                       , "Dacca"               , "Asie"    , "bd"),
                new Countries("Barbade"                          , "BridGetown"          , "Amerique", "bb"),
                new Countries("Belgique"                         , "Bruxelles"           , "Europe"  , "be"),
                new Countries("Belize"                           , "Belmopan"            , "Amerique", "bz"),
                new Countries("Benin"                            , "Porto-Novo"          , "Afrique" , "bj"),
                new Countries("Bhoutan"                          , "Thimbu"              , "Asie"    , "bt"),
                new Countries("Bielorussie"                      , "Minsk"               , "Europe"  , "by"),
                new Countries("Birmanie"                         , "Naypyidaw"           , "Asie"    , "mm"),
                new Countries("Bolivie"                          , "Sucre"               , "Amerique", "bo"),
                new Countries("Bosnie-Herzegovine"               , "Sarajevo"            , "Europe"  , "ba"),
                new Countries("Botswana"                         , "Gaborone"            , "Afrique" , "bw"),
                new Countries("Bresil"                           , "Brasilia"            , "Amerique", "br"),
                new Countries("Brunei"                           , "Bandar Seri Begawan" , "Asie"    , "bn"),
                new Countries("Bulgarie"                         , "Sofia"               , "Europe"  , "bg"),
                new Countries("Burkina Faso"                     , "Ouagadougou"         , "Afrique" , "bf"),
                new Countries("Burundi"                          , "Bujumbura"           , "Afrique" , "bi"),
                new Countries("Cambodge"                         , "Phnom Penh"          , "Asie"    , "kh"),
                new Countries("Cameroun"                         , "Yaounde"             , "Afrique" , "cm"),
                new Countries("Canada"                           , "Ottawa"              , "Amerique", "ca"),
                new Countries("Cap-Vert"                         , "Praia"               , "Afrique" , "cv"),
                new Countries("Chili"                            , "Santiago"            , "Amerique", "cl"),
                new Countries("Chine"                            , "Pekin"               , "Asie"    , "cn"),
                new Countries("Chypre"                           , "Nicosie"             , "Europe"  , "cy"),
                new Countries("Colombie"                         , "Bogota"              , "Amerique", "co"),
                new Countries("Comores"                          , "Moroni"              , "Afrique" , "km"),
                new Countries("Congo"                            , "Brazzaville"         , "Afrique" , "cg"),
                new Countries("Coree du Nord"                    , "Pyongyang"           , "Asie"    , "kp"),
                new Countries("Coree du Sud"                     , "Seoul"               , "Asie"    , "kr"),
                new Countries("Costa Rica"                       , "San Jose"            , "Amerique", "cr"),
                new Countries("Cote d'Ivoire"                    , "Yamoussoukro"        , "Afrique" , "ci"),
                new Countries("Croatie"                          , "Zagreb"              , "Europe"  , "hr"),
                new Countries("Cuba"                             , "La Havane"           , "Amerique", "cu"),
                new Countries("Danemark"                         , "Copenhague"          , "Europe"  , "dk"),
                new Countries("Djibouti"                         , "Djibouti"            , "Afrique" , "dj"),
                new Countries("Dominique"                        , "Roseau"              , "Amerique", "dm"),
                new Countries("Egypte"                           , "Le Caire"            , "Afrique" , "eg"),
                new Countries("Emirats Arabes Unis"              , "Abu Dhabi"           , "Asie"    , "ae"),
                new Countries("Equateur"                         , "Quito"               , "Amerique", "ec"),
                new Countries("Erythree"                         , "Asmara"              , "Afrique" , "er"),
                new Countries("Espagne"                          , "Madrid"              , "Europe"  , "es"),
                new Countries("Estonie"                          , "Tallinn"             , "Europe"  , "ee"),
                new Countries("Eswatini"                         , "Mbabane"             , "Afrique" , "sz"),
                new Countries("Etats-Unis"                       , "Washington"          , "Amerique", "us"),
                new Countries("Ethiopie"                         , "Addis-Abeba"         , "Afrique" , "et"),
                new Countries("Fidji"                            , "Suva"                , "Oceanie" , "fj"),
                new Countries("Finlande"                         , "Helsinki"            , "Europe"  , "fi"),
                new Countries("France"                           , "Paris"               , "Europe"  , "fr"),
                new Countries("Gabon"                            , "Libreville"          , "Afrique" , "ga"),
                new Countries("Gambie"                           , "Banjul"              , "Afrique" , "gm"),
                new Countries("Georgie"                          , "Tbilissi"            , "Asie"    , "ge"),
                new Countries("Ghana"                            , "Accra"               , "Afrique" , "gh"),
                new Countries("Grece"                            , "Athenes"             , "Europe"  , "gr"),
                new Countries("Grenade"                          , "Saint George's"      , "Amerique", "gd"),
                new Countries("Guatemala"                        , "Guatemala"           , "Amerique", "gt"),
                new Countries("Guinee"                           , "Conakry"             , "Afrique" , "gn"),
                new Countries("Guinee equatoriale"               , "Malabo"              , "Afrique" , "gq"),
                new Countries("Guinee-Bissau"                    , "Bissau"              , "Afrique" , "gw"),
                new Countries("Guyana"                           , "GeorGetown"          , "Amerique", "gy"),
                new Countries("Haiti"                            , "Port-au-Prince"      , "Amerique", "ht"),
                new Countries("Honduras"                         , "Tegucigalpa"         , "Amerique", "hn"),
                new Countries("Hongrie"                          , "Budapest"            , "Europe"  , "hu"),
                new Countries("Maurice"                          , "Port Louis"          , "Afrique" , "mu"),
                new Countries("Inde"                             , "New Delhi"           , "Asie"    , "in"),
                new Countries("Indonesie"                        , "Jakarta"             , "Asie"    , "id"),
                new Countries("Irak"                             , "Bagdad"              , "Asie"    , "iq"),
                new Countries("Iran"                             , "Teheran"             , "Asie"    , "ir"),
                new Countries("Irlande"                          , "Dublin"              , "Europe"  , "ie"),
                new Countries("Islande"                          , "Reykjavik"           , "Europe"  , "is"),
                new Countries("Israel"                           , "Jerusalem"           , "Asie"    , "il"),
                new Countries("Italie"                           , "Rome"                , "Europe"  , "it"),
                new Countries("Jamaique"                         , "Kingston"            , "Amerique", "jm"),
                new Countries("Japon"                            , "Tokyo"               , "Asie"    , "jp"),
                new Countries("Jordanie"                         , "Amman"               , "Asie"    , "jo"),
                new Countries("Kazakhstan"                       , "Astana"              , "Asie"    , "kz"),
                new Countries("Kenya"                            , "Nairobi"             , "Afrique" , "ke"),
                new Countries("Kirghizistan"                     , "Bichkek"             , "Asie"    , "kg"),
                new Countries("Kiribati"                         , "Tarawa"              , "Oceanie" , "ki"),
                new Countries("Kosovo"                           , "Pristina"            , "Europe"  , "xk"),
                new Countries("Koweit"                           , "Koweit"              , "Asie"    , "kw"),
                new Countries("Laos"                             , "Vientiane"           , "Asie"    , "la"),
                new Countries("Lesotho"                          , "Maseru"              , "Afrique" , "ls"),
                new Countries("Lettonie"                         , "Riga"                , "Europe"  , "lv"),
                new Countries("Liban"                            , "Beyrouth"            , "Asie"    , "lb"),
                new Countries("Liberia"                          , "Monrovia"            , "Afrique" , "lr"),
                new Countries("Libye"                            , "Tripoli"             , "Afrique" , "ly"),
                new Countries("Liechtenstein"                    , "Vaduz"               , "Europe"  , "li"),
                new Countries("Lituanie"                         , "Vilnius"             , "Europe"  , "lt"),
                new Countries("Luxembourg"                       , "Luxembourg"          , "Europe"  , "lu"),
                new Countries("Macedoine du Nord"                , "Skopje"              , "Europe"  , "mk"),
                new Countries("Madagascar"                       , "Antananarivo"        , "Afrique" , "mg"),
                new Countries("Malaisie"                         , "Kuala Lumpur"        , "Asie"    , "my"),
                new Countries("Malawi"                           , "Lilongwe"            , "Afrique" , "mw"),
                new Countries("Maldives"                         , "Male"                , "Asie"    , "mv"),
                new Countries("Mali"                             , "Bamako"              , "Afrique" , "ml"),
                new Countries("Malte"                            , "La Valette"          , "Europe"  , "mt"),
                new Countries("Maroc"                            , "Rabat"               , "Afrique" , "ma"),
                new Countries("Marshall"                         , "Majuro"              , "Oceanie" , "mh"),
                new Countries("Mauritanie"                       , "Nouakchott"          , "Afrique" , "mr"),
                new Countries("Mexique"                          , "Mexico"              , "Amerique", "mx"),
                new Countries("Micronesie"                       , "Palikir"             , "Oceanie" , "fm"),
                new Countries("Moldavie"                         , "Chisinau"            , "Europe"  , "md"),
                new Countries("Monaco"                           , "Monaco"              , "Europe"  , "mc"),
                new Countries("Mongolie"                         , "Oulan-Bator"         , "Asie"    , "mn"),
                new Countries("Montenegro"                       , "Podgorica"           , "Europe"  , "me"),
                new Countries("Mozambique"                       , "Maputo"              , "Afrique" , "mz"),
                new Countries("Namibie"                          , "Windhoek"            , "Afrique" , "na"),
                new Countries("Nauru"                            , "Yaren"               , "Oceanie" , "nr"),
                new Countries("Nepal"                            , "Katmandou"           , "Asie"    , "np"),
                new Countries("Nicaragua"                        , "Managua"             , "Amerique", "ni"),
                new Countries("Niger"                            , "Niamey"              , "Afrique" , "ne"),
                new Countries("Nigeria"                          , "Abuja"               , "Afrique" , "ng"),
                new Countries("Norvege"                          , "Oslo"                , "Europe"  , "no"),
                new Countries("Nouvelle-Zelande"                 , "Wellington"          , "Oceanie" , "nz"),
                new Countries("Oman"                             , "Mascate"             , "Asie"    , "om"),
                new Countries("Ouganda"                          , "Kampala"             , "Afrique" , "ug"),
                new Countries("Ouzbekistan"                      , "Tachkent"            , "Asie"    , "uz"),
                new Countries("Pakistan"                         , "Islamabad"           , "Asie"    , "pk"),
                new Countries("Palaos"                           , "Melekeok"            , "Oceanie" , "pw"),
                new Countries("Palestine"                        , "Jerusalem-Est"       , "Asie"    , "ps"),
                new Countries("Panama"                           , "Panama"              , "Amerique", "pa"),
                new Countries("Papouasie-Nouvelle-Guinee"        , "Port Moresby"        , "Oceanie" , "pg"),
                new Countries("Paraguay"                         , "Asuncion"            , "Amerique", "py"),
                new Countries("Pays-Bas"                         , "Amsterdam"           , "Europe"  , "nl"),
                new Countries("Perou"                            , "Lima"                , "Amerique", "pe"),
                new Countries("Philippines"                      , "Manille"             , "Asie"    , "ph"),
                new Countries("Pologne"                          , "Varsovie"            , "Europe"  , "pl"),
                new Countries("Portugal"                         , "Lisbonne"            , "Europe"  , "pt"),
                new Countries("Qatar"                            , "Doha"                , "Asie"    , "qa"),
                new Countries("Republique Centrafricaine"        , "Bangui"              , "Afrique" , "cf"),
                new Countries("Republique Democratique du Congo" , "Kinshasa"            , "Afrique" , "cd"),
                new Countries("Republique Dominicaine"           , "Saint-Domingue"      , "Amerique", "do"),
                new Countries("Tchequie"                         , "Prague"              , "Europe"  , "cz"),
                new Countries("Roumanie"                         , "Bucarest"            , "Europe"  , "ro"),
                new Countries("Royaume-Uni"                      , "Londres"             , "Europe"  , "gb"),
                new Countries("Russie"                           , "Moscou"              , "Europe"  , "ru"),
                new Countries("Rwanda"                           , "Kigali"              , "Afrique" , "rw"),
                new Countries("Saint-Christophe-et-Nieves"       , "BasSeterre"          , "Amerique", "kn"),
                new Countries("Saint-Marin"                      , "Saint-Marin"         , "Europe"  , "sm"),
                new Countries("Saint-Vincent-et-les-Grenadines"  , "Kingstown"           , "Amerique", "vc"),
                new Countries("Sainte-Lucie"                     , "Castries"            , "Amerique", "lc"),
                new Countries("Salomon"                          , "Honiara"             , "Oceanie" , "sb"),
                new Countries("Salvador"                         , "San Salvador"        , "Amerique", "sv"),
                new Countries("Samoa"                            , "Apia"                , "Oceanie" , "ws"),
                new Countries("Sao Tome et Principe"             , "Sao Tome"            , "Afrique" , "st"),
                new Countries("Senegal"                          , "Dakar"               , "Afrique" , "sn"),
                new Countries("Serbie"                           , "Belgrade"            , "Europe"  , "rs"),
                new Countries("Seychelles"                       , "Victoria"            , "Afrique" , "sc"),
                new Countries("Sierra Leone"                     , "Freetown"            , "Afrique" , "sl"),
                new Countries("Singapour"                        , "Singapour"           , "Asie"    , "sg"),
                new Countries("Slovaquie"                        , "Bratislava"          , "Europe"  , "sk"),
                new Countries("Slovenie"                         , "Ljubljana"           , "Europe"  , "si"),
                new Countries("Somalie"                          , "Mogadiscio"          , "Afrique" , "so"),
                new Countries("Soudan"                           , "Khartoum"            , "Afrique" , "sd"),
                new Countries("Soudan du Sud"                    , "Djouba"              , "Afrique" , "ss"),
                new Countries("Sri Lanka"                        , "Sri Jayawardenapura" , "Asie"    , "lk"),
                new Countries("Suede"                            , "Stockholm"           , "Europe"  , "se"),
                new Countries("Suisse"                           , "Berne"               , "Europe"  , "ch"),
                new Countries("Suriname"                         , "Paramaribo"          , "Amerique", "sr"),
                new Countries("Syrie"                            , "Damas"               , "Asie"    , "sy"),
                new Countries("Tadjikistan"                      , "Douchanbe"           , "Asie"    , "tj"),
                new Countries("Taiwan"                           , "Taipei"              , "Asie"    , "tw"),
                new Countries("Tanzanie"                         , "Dodoma"              , "Afrique" , "tz"),
                new Countries("Tchad"                            , "N'Djamena"           , "Afrique" , "td"),
                new Countries("Thailande"                        , "Bangkok"             , "Asie"    , "th"),
                new Countries("Timor-Oriental"                   , "Dili"                , "Oceanie" , "tl"),
                new Countries("Togo"                             , "Lome"                , "Afrique" , "tg"),
                new Countries("Tonga"                            , "Nukualofa"           , "Oceanie" , "to"),
                new Countries("Trinite-et-Tobago"                , "Port d'Espagne"      , "Amerique", "tt"),
                new Countries("Tunisie"                          , "Tunis"               , "Afrique" , "tn"),
                new Countries("Turkmenistan"                     , "Achgabat"            , "Asie"    , "tm"),
                new Countries("Turquie"                          , "Ankara"              , "Asie"    , "tr"),
                new Countries("Tuvalu"                           , "Fanafuti"            , "Oceanie" , "tv"),
                new Countries("Ukraine"                          , "Kiev"                , "Europe"  , "ua"),
                new Countries("Uruguay"                          , "Montevideo"          , "Amerique", "uy"),
                new Countries("Vanuatu"                          , "Port-Vila"           , "Oceanie" , "vu"),
                new Countries("Vatican"                          , "Vatican"             , "Europe"  , "va"),
                new Countries("Venezuela"                        , "Caracas"             , "Amerique", "ve"),
                new Countries("Viet Nam"                         , "Hanoi"               , "Asie"    , "vn"),
                new Countries("Yemen"                            , "Sanaa"               , "Asie"    , "ye"),
                new Countries("Zambie"                           , "Lusaka"              , "Afrique" , "zm"),
                new Countries("Zimbabwe"                         , "Harare"              , "Afrique" , "zw"),
            };
        public CountriesDatas()
        {
        }

    }
}
